### ISSUE TITLE
bugs jump into games when they spawn

### ISSUE THREAD

**Issue by joesturge** [CiaranWoodward/LD55#1]

**Comment by CiaranWoodward** [comment]
50121e23da6c02540f8fece7faecfef3cab5a1c5

**Comment by joesturge** [comment]
I think we need to make bugs wonder more when they first spawn, so that the game can be lost, if they kill themselves too quick you would never have enough to loose the game as we have so many cats wondering around

alternativly make bugs kill multiple creates before they despawn

**Comment by CiaranWoodward** [comment]
I vote for B
